### ISSUE TITLE
VIP Playlist stopped working

### ISSUE THREAD

**Issue by valtor** [fpgaminer/vip-html5-player#14]
Not sure what happened, but the website (http://fpgaminer.github.io/vip-html5-player/ not http://vip.aersia.net/vip.swf ) isn't working, specifically on the VIP playlist. If I switch playlists, then the website works normally... I tried on multiple browsers and multiple devices.

**Comment by fpgaminer** [comment]
Seems to be a problem with the playlist from aersia.net.  The playlist file itself (http://vip.aersia.net/roster.xml) has an extra `>` at the end for some reason.  That means the browser throws up trying to read it.

I'll see if I can think of a reasonable workaround, but otherwise there's not much I can do...

**Comment by fpgaminer** [comment]
Seems to work now.
