### ISSUE TITLE
Not working under https?

### ISSUE THREAD

**Issue by Fruglemonkey** [fpgaminer/vip-html5-player#9]
I'm trying to host this under https to do some voice control experimentation, and I've found that it doesn't work.

https://jeffl.ai/Test
http://jeffl.ai/Test

Tested under firefox and Chrome.

**Comment by Fruglemonkey** [comment]
Ah, it's complaining about scripts from unsecure sources. Jquery and the css can both be retrieved over https, but not so for whateverorigin: https://github.com/ripper234/Whatever-Origin/issues/18

**Comment by Fruglemonkey** [comment]
Tried PR https://github.com/fpgaminer/vip-html5-player/pull/8, looks like this issue wont be fixable unless someone hosts an https mirror of the playlists, or if aersia itself provides https.

For now I'll just mirror the playlists myself, which works (Using the PR): https://jeffl.ai/Test/https.html

**Comment by khanfx** [comment]
You could consider using an off-the-shelf HTTPS proxy service like https://hide.me/en/proxy

https://proxy-nl.hide.me/go.php?u=AYR0w7LjvVNnvmy7VhXCd5NGIcwocs%2B%2Beav1bg%3D%3D&b=5&f=norefer

**Comment by Fruglemonkey** [comment]
Personally I'd prefer not using third party proxies, as their reliability and availability isn't always 100% (Such as whateverorigin which has since stop being actively maintained...)

**Comment by fpgaminer** [comment]
I've merged PR#8, and made the javascript and css external urls use "//", so that fixes everything for HTTPS except loading the playlist XML files.  Seems browsers are currently okay with loading the media files over HTTP (though they still throw a warning).  So we only need to fix the playlist files.  I could probably do that by mirroring them in the repo and having javascript use the local copies for HTTPS.  The downside is that they'll become outdated and I'll have to update them on a regular basis.

Or we could ask cats777 to get a verified SSL cert for the domains.  Let's Encrypt makes that free these days.  But I don't typically like asking cats777 to do extra work on top of already providing us with these wonderful collections of music.

**Comment by Fruglemonkey** [comment]
> But I don't typically like asking cats777 to do extra work on top of already providing us with these wonderful collections of music.

I agree. Seems like the workload is too much for too little of a gain, especially when someone that wants https support can simply locally host the playlists themselves. I'll consider this a non-issue, but I'll leave it up to you to close it if you want.

**Comment by nihey** [comment]
I'm currently maintaining a `https` reverse proxy of the original `xml`s, so they'll always be updated - I've used it on [my version of vip player](https://nihey.github.io/aersia). @fpgaminer You can use them if you want:
- https://aersia.nihey.org/roster.xml
- https://aersia.nihey.org/roster-mellow.xml
- and so on

**Comment by fpgaminer** [comment]
aersia.net has HTTPS now.  Fixed by https://github.com/fpgaminer/vip-html5-player/pull/13
